### PR TITLE
P-Hacking

### PR DESCRIPTION
**Pull request by andrewjkim**
I made a _super_ brief and loose outline for p-hacking. I feel like it's a pretty broad topic, and the topics covered in the guest lectures are pretty varied, so I'm not sure what is worth going over and what isn't.

Also I'm not sure if I should be making a new folder or something

### CODE REVIEW

**Comment by SamLau95** [comment]
This is going to be a section in the hypothesis testing chapter so let's leave the notebook in `notebooks/ch18/`.

Deb and I decided to limit this section to multiple testing (running a hypothesis test on the same data multiple times). This means that we'll avoid talking about researcher or sample bias. Instead, we should talk about why multiple testing is misleading and how to avoid implicit multiple testing by not performing EDA and a hypothesis test on the same dataset.

**Comment by andrewjkim** [comment]
A few notes on what I've written:
- I think for the most part the Paul the Octopus section seems okay (unless more detail should be added)
- I'm not entirely sure what to title the part on p-values being the tip of the iceberg
- I'm also not entirely sure how much to write on that, being that the conclusion of the paper is something along the lines of "we should educate scientists better on how to deal with the data pipeline better."

**Comment by andrewjkim** [comment]
It seems like the data included in the nutrition study has a lot of things going on, and I'm not 100% what I should be looking at for the csv. Also, they use an R script to run the p-values and I am extremely unfamiliar with R.

As for the A/B testing section, I have a couple of questions. When drawing from the Gaussian, what are the values drawn from the guassian representing? What should I use as my standard deviation, and how do I show that the p-values get "hacked?"

**Comment by SamLau95** [comment]
Congrats! One thing I miss from Berkeley is the grapefruit Radler beer you can find (though it's a bit challenging to spot) at Safeway—get a pack now that you can :).

The idea in the nutrition study is to take the raw CSV file and see if you can find significant associations that don't make any sense. For example, there's a table in the article that shows a bunch of dumb associations like raw tomatoes with Judaism. You don't need to look at the R script at all; you can just look at the columns of the CSV and pick pairs of columns to run multiple hypothesis tests on until you get some results.

The assumption here is that none of the ad choices have any effect at all on the engagement (e.g. click-through rate). However, there is some natural variation in the engagement; this is what the Gaussian is modeling. It's centered at 0 (no overall effect) but has some variance (to show the variation in measurement). You can just pick a variance that seems reasonable and gives good results.

The idea is that even though when there's no overall effect in changing the ad, if you keep running A/B tests you'll get a "significant" result. This basically means: draw a sample from the population where some people went through ad A and some through ad B. Run a hypothesis test on the difference in mean engagement. Repeat until you get a significant result. This emulates trying many (A/B/C/D/...) alternatives of the same ad. We happen to know that none of the alternatives are any different from the original and yet we get a significant result anyway because of p-hacking.

**Comment by andrewjkim** [comment]
Okay, so I think I'm almost there. I'd definitely be willing to work an extra week on this to just wrap it all up (especially since I haven't been having much time to do this given it's also my couple weeks of my internship). 

I did the p-value stuff for the nutritional data, but I'm not sure what would look best. A lot of the labels are nondescript, so it's hard to figure out what I'm looking at. Is it safe to just copy a few of the correlations they use in the 538 article?
As for the A/B testing, I think I'm still a bit confused as to how to do the permutation tests properly. I feel that since I'm permuting on random values, and then comparing those values to also random values, it's a very low chance (unless all 100 samples are near-outliers) that I get a value that I can work with, unless I'm doing something wrong lol

**Comment by SamLau95** [comment]
Glad to see you're making progress!

>  did the p-value stuff for the nutritional data, but I'm not sure what would look best. A lot of the labels are nondescript, so it's hard to figure out what I'm looking at. Is it safe to just copy a few of the correlations they use in the 538 article?

Yup, feel free to copy a few correlations and make your best guesses as to what the data columns mean. You can probably infer many column meanings from the article.

> As for the A/B testing, I think I'm still a bit confused as to how to do the permutation tests properly. I feel that since I'm permuting on random values, and then comparing those values to also random values, it's a very low chance (unless all 100 samples are near-outliers) that I get a value that I can work with, unless I'm doing something wrong lol

You aren't performing a permutation test in your code. I see that you draw one sample for A and one for B. To perform a permutation test, you need to:

1. Compute the observed test statistic: abs(mean(B) - mean(A))
2. Shuffle the data between A and B. That is, take all the points, concat them into one long array, shuffle the array, then reassign the first half to A* and the second half B*. Compute the test statistic on the resampled A* and B*.
3. Repeat (2). 1000 times should be enough.
4. The p-value is the proportion of resampled test statistics that are equal to or larger than the observed test statistic.

Here's some code I wrote to run a permutation test you can edit:

```python
n = 50

landing_pages = [np.random.normal(0, 0.1, n) for _ in range(15)]

A = landing_pages[0]
B = landing_pages[1]

def test_stat(A, B):
    return np.abs(np.mean(B) - np.mean(A))

obs = test_stat(A, B)
obs

reps = 1000

def permute(A, B):
    combined = np.append(A, B)
    shuffled = np.random.choice(combined, size=len(combined), replace=False)
    return shuffled[:n], shuffled[n:]

resampled = [test_stat(*permute(A, B)) for _ in range(reps)]
resampled[:5]

landing_pages = [np.random.normal(0, 0.1, 50) for _ in range(15)]

p_val = np.count_nonzero(obs >= resampled) / reps
p_val
```

**Comment by andrewjkim** [comment]
I made the permutation test changes - I'm starting to notice some weird discrepancies in my p-values when compared to the ones in the 358 repo. My values are smaller than theirs by multiple magnitudes. I'm not sure what's wrong, unless I'm using the wrong library to calculate my p-values?

**Comment by SamLau95** [comment]
It looks like their code runs a linear regression between each pair of variables, then computes a p-value under the null hypothesis that the slope == 0. Doing a hypothesis test like this asks the question: "Is a change in x associated in a change in y?"

Your code runs a t-test for the difference in means between each pair of variables which tests a different question—"Do the average value of x and y differ?"

Luckily, it looks like scipy has a function to compute the p-value for the first hypothesis: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.pearsonr.html

**Comment by SamLau95** [comment]
@andrewjkim Heya, think you can merge from master and push again? There was a big re-org that happened last week. Your notebook should end up in the `notebooks/ch/18` folder.

**Comment by andrewjkim** [comment]
Okay - I reverted everything back to how it was directly after I pulled. Can you just real quick verify that that's right? 

And once that's good, then all I should have to do is add my hyp_phacking.ipynb file into ch/18/ and then add it to the toc, right?

**Comment by SamLau95** [comment]
That looks good to me. I think the easiest way to make things work is to delete all changes except your notebook and your data. Then, you can pull from master, move the notebook / data into the correct folder, and build again.

**Pull request merged**
