### PR TITLE
Studentized Bootstrap ~continued~

### PR DESCRIPTION
**Pull request by andrewjkim**
For @SamLau95 to make more comments in!

### CODE REVIEW

**Comment by andrewjkim** [comment]
Just a few questions about the labels. 

- What is the proper term for the fraction of confidence intervals that contain the population statistic? Is it just "coverage?"
- I'm having some Latex issues with having the thetas display in titles. 
- What is the proper term for the y-label in a distribution plot? Should I leave it blank, or should I say "count?"

**Comment by SamLau95** [comment]
1. Yup, "coverage" (short for coverage probability, it seems: https://www.wikiwand.com/en/Coverage_probability ) refers to the actual probability that a CI will contain the population parameter. "Coverage error" refers to the difference between the coverage and the desired confidence.
1. You should use raw Python strings for the plot titles: `r'$\hat{\theta}$'` instead of `'$\hat{\theta}$'`.
1. For histograms, you should use the `normed=True` option and use the y-axis label: "Proportion per unit".

**Comment by andrewjkim** [comment]
Sorry for addressing the comments so late! I think I need to do some extra stuff with the data before using normed=True, since it seems to be making weird values, unless I'm not understanding something properly.

**Comment by SamLau95** [comment]
The histogram axes look correct as they are right now. Since we're norming the histogram, the entire histrogram area should sum to 1. Since our x-axis ranges from 300-600, the y-axis units should have around 3 decimal places.

Some questions I have:

1. I see that you've left in the simulated `times` data. Did you mean to substitute in the actual repair times data?
1. Can you describe the data in some more detail? What population do the data represent? And what units are the times in? Do you have a link to the original data? You should also state that the data is a census.
1. The `np.mean` of the population gives 356.5 but you state that "we can see that actual average repair time is about 354." Did you mean to change this number?
1. The side-by-side histogram comparison should have titles and axis labels.

Otherwise, this looks great! I'm going to approve it so feel free to merge away after you add your section to the `SUMMARY.md` :) .

**Comment by andrewjkim** [comment]
Gonna hold off on merging for now - there's a couple merge conflicts that I don't know how to handle since it's in the html file, and I originally was accidentally using the randomly generated data, so I had to swap it out.

Additionally, there is no information given about the particular data, it is just said that "The data for one combination of CLEC, class of service, and period are shown in Table 1 and Figure 1." in https://www.tandfonline.com/doi/full/10.1080/00031305.2015.1089789?scroll=top&needAccess=true

**Pull request merged**
